CREATE OR REPLACE TABLE `tcc-tsi.microdados_enem_2022.dim_questionario_socioeconomico` (
    NU_INSCRICAO STRING OPTIONS(description="Número de inscrição do participante"),
    Q001 STRING OPTIONS(description="Grau de instrução do pai ou responsável do participante"),
    Q002 STRING OPTIONS(description="Grau de instrução da mãe ou responsável do participante"),
    Q003 STRING OPTIONS(description="Grupo ocupacional do pai ou responsável do participante"),
    Q004 STRING OPTIONS(description="Grupo ocupacional da mãe ou responsável do participante"),
    Q005 STRING OPTIONS(description="Número de pessoas com quem o participante mora"),
    Q006 STRING OPTIONS(description="Faixa de renda familiar do participante"),
    Q007 STRING OPTIONS(description="Frequência de leitura de livros pelo participante"),
    Q008 STRING OPTIONS(description="Quantidade de banheiros na casa do participante"),
    Q009 STRING OPTIONS(description="Quantidade de micro-ondas na casa do participante"),
    Q010 STRING OPTIONS(description="Quantidade de geladeiras na casa do participante"),
    Q011 STRING OPTIONS(description="Quantidade de telefones celulares na casa do participante"),
    Q012 STRING OPTIONS(description="Quantidade de telefones fixos na casa do participante"),
    Q013 STRING OPTIONS(description="Quantidade de computadores na casa do participante"),
    Q014 STRING OPTIONS(description="Quantidade de televisores na casa do participante"),
    Q015 STRING OPTIONS(description="Quantidade de TVs por assinatura na casa do participante"),
    Q016 STRING OPTIONS(description="Quantidade de carros na casa do participante"),
    Q017 STRING OPTIONS(description="Quantidade de motos na casa do participante"),
    Q018 STRING OPTIONS(description="Possui máquina de lavar roupa"),
    Q019 STRING OPTIONS(description="Quantidade de máquinas de lavar roupa na casa do participante"),
    Q020 STRING OPTIONS(description="Possui DVD na casa do participante"),
    Q021 STRING OPTIONS(description="Possui máquina de secar roupa"),
    Q022 STRING OPTIONS(description="Quantidade de máquinas de lavar louça na casa do participante"),
    Q023 STRING OPTIONS(description="Possui freezer na casa do participante"),
    Q024 STRING OPTIONS(description="Quantidade de fornos elétricos na casa do participante"),
    Q025 STRING OPTIONS(description="Possui aspirador de pó na casa do participante")
);
