INSERT INTO `tcc-tsi.microdados_enem_2022.dim_dados_da_redacao` (
    NU_INSCRICAO,
    NU_NOTA_REDACAO,
    TP_STATUS_REDACAO,
    NU_NOTA_COMP1,
    NU_NOTA_COMP2,
    NU_NOTA_COMP3,
    NU_NOTA_COMP4,
    NU_NOTA_COMP5
)
SELECT 
    NU_INSCRICAO,
    CAST(NU_NOTA_REDACAO AS FLOAT64) AS NU_NOTA_REDACAO,
    TP_STATUS_REDACAO,
    CAST(NU_NOTA_COMP1 AS FLOAT64) AS NU_NOTA_COMP1,
    CAST(NU_NOTA_COMP2 AS FLOAT64) AS NU_NOTA_COMP2,
    CAST(NU_NOTA_COMP3 AS FLOAT64) AS NU_NOTA_COMP3,
    CAST(NU_NOTA_COMP4 AS FLOAT64) AS NU_NOTA_COMP4,
    CAST(NU_NOTA_COMP5 AS FLOAT64) AS NU_NOTA_COMP5
FROM 
    `tcc-tsi.microdados_enem_2022.enrich_microdados_enem_2022`;
